spring:
  application:
    name: lolstats
  profiles:
    active: dev
  jackson:
    deserialization:
      fail-on-unknown-properties: false

ddragon:
  base-url: https://ddragon.leagueoflegends.com
  refresh-interval-hours: 24
