spring:
  datasource:
    url: jdbc:mysql://localhost:3307/lolstats
    username: ${DB_USERNAME:lolstats}
    password: ${DB_PASSWORD:lolstats}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

riot:
  api:
    key: ${RIOT_API_KEY}
    platform-url: https://kr.api.riotgames.com
    regional-url: https://asia.api.riotgames.com

app:
  cache:
    summoner-ttl-minutes: 10
